# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/transsion/mt6789-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter X6837 X6833B X676C X6853 S666LN,$(TARGET_DEVICE)),)

endif
